# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
development:
  adapter: postgresql
  database: sam_development
  pool: 5
  host: localhost
  username: samira
  password: samira123
  timeout: 5000
  
test:
  adapter: postgresql
  database: sam_test
  pool: 5
  host: localhost
  username: samira
  password: samira123
  timeout: 5000

